// <auto-generated />
using System;
using IoT_Sensor_Monitoring_Web_App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IoT_Sensor_Monitoring_Web_App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251129023653_InitialCreateFixed")]
    partial class InitialCreateFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IoT_Sensor_Monitoring_Web_App.Models.Alert", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertId"));

                    b.Property<int>("AlertRuleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.Property<int>("ReadingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AlertId");

                    b.HasIndex("AlertRuleId");

                    b.HasIndex("ReadingId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("IoT_Sensor_Monitoring_Web_App.Models.AlertRule", b =>
                {
                    b.Property<int>("AlertRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertRuleId"));

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<double>("ThresholdValue")
                        .HasColumnType("float");

                    b.HasKey("AlertRuleId");

                    b.HasIndex("SensorId");

                    b.ToTable("AlertRules");
                });

            modelBuilder.Entity("IoT_Sensor_Monitoring_Web_App.Models.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeviceTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeviceId");

                    b.HasIndex("DeviceTypeId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("IoT_Sensor_Monitoring_Web_App.Models.DeviceType", b =>
                {
                    b.Property<int>("DeviceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceTypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeviceTypeId");

                    b.ToTable("DeviceTypes");
                });

            modelBuilder.Entity("IoT_Sensor_Monitoring_Web_App.Models.RetentionPolicy", b =>
                {
                    b.Property<int>("RetentionPolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RetentionPolicyId"));

                    b.Property<int>("DaysToKeep")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RetentionPolicyId");

                    b.ToTable("RetentionPolicies");
                });

            modelBuilder.Entity("IoT_Sensor_Monitoring_Web_App.Models.Sensor", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SensorId"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SensorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SensorId");

                    b.HasIndex("DeviceId");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("IoT_Sensor_Monitoring_Web_App.Models.SensorReading", b =>
                {
                    b.Property<int>("ReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReadingId"));

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("ReadingId");

                    b.HasIndex("SensorId");

                    b.ToTable("SensorReadings");
                });

            modelBuilder.Entity("IoT_Sensor_Monitoring_Web_App.Models.SystemSetting", b =>
                {
                    b.Property<int>("SystemSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SystemSettingId"));

                    b.Property<int?>("CurrentRetentionPolicyId")
                        .HasColumnType("int");

                    b.HasKey("SystemSettingId");

                    b.HasIndex("CurrentRetentionPolicyId");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("IoT_Sensor_Monitoring_Web_App.Models.Alert", b =>
                {
                    b.HasOne("IoT_Sensor_Monitoring_Web_App.Models.AlertRule", "AlertRule")
                        .WithMany("Alerts")
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IoT_Sensor_Monitoring_Web_App.Models.SensorReading", "Reading")
                        .WithMany("Alerts")
                        .HasForeignKey("ReadingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlertRule");

                    b.Navigation("Reading");
                });

            modelBuilder.Entity("IoT_Sensor_Monitoring_Web_App.Models.AlertRule", b =>
                {
                    b.HasOne("IoT_Sensor_Monitoring_Web_App.Models.Sensor", "Sensor")
                        .WithMany("AlertRules")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("IoT_Sensor_Monitoring_Web_App.Models.Device", b =>
                {
                    b.HasOne("IoT_Sensor_Monitoring_Web_App.Models.DeviceType", "DeviceType")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceType");
                });

            modelBuilder.Entity("IoT_Sensor_Monitoring_Web_App.Models.Sensor", b =>
                {
                    b.HasOne("IoT_Sensor_Monitoring_Web_App.Models.Device", "Device")
                        .WithMany("Sensors")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("IoT_Sensor_Monitoring_Web_App.Models.SensorReading", b =>
                {
                    b.HasOne("IoT_Sensor_Monitoring_Web_App.Models.Sensor", "Sensor")
                        .WithMany("Readings")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("IoT_Sensor_Monitoring_Web_App.Models.SystemSetting", b =>
                {
                    b.HasOne("IoT_Sensor_Monitoring_Web_App.Models.RetentionPolicy", "CurrentRetentionPolicy")
                        .WithMany()
                        .HasForeignKey("CurrentRetentionPolicyId");

                    b.Navigation("CurrentRetentionPolicy");
                });

            modelBuilder.Entity("IoT_Sensor_Monitoring_Web_App.Models.AlertRule", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("IoT_Sensor_Monitoring_Web_App.Models.Device", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("IoT_Sensor_Monitoring_Web_App.Models.DeviceType", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("IoT_Sensor_Monitoring_Web_App.Models.Sensor", b =>
                {
                    b.Navigation("AlertRules");

                    b.Navigation("Readings");
                });

            modelBuilder.Entity("IoT_Sensor_Monitoring_Web_App.Models.SensorReading", b =>
                {
                    b.Navigation("Alerts");
                });
#pragma warning restore 612, 618
        }
    }
}
